version: "3"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_USER: dummy
      MARIADB_PASSWORD: it-is-not-safe
      MARIADB_ROOT_PASSWORD: super-secret
      MARIADB_DATABASE: public
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: it-is-not-safe
      POSTGRES_DB: public
    ports:
      - "5432:5432"